apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "mongodb-replicaset.name" . }}
    chart: {{ template "mongodb-replicaset.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
  name: {{ template "mongodb-replicaset.fullname" . }}-init
  namespace: {{ template "mongodb-replicaset.namespace" . }}
data:
  on-start.sh: |
{{ .Files.Get "init/on-start.sh" | indent 4 }}
  new-on-start.sh: |
{{ .Files.Get "init/new-on-start.sh" | indent 4 }}
  configure_persisted_replica.js: |
{{ .Files.Get "init/configure_persisted_replica.js" | indent 4 }}
  turn_off_writeconcern.js: |
{{ .Files.Get "init/turn_off_writeconcern.js" | indent 4 }}
  configure_primary.js: |
{{ .Files.Get "init/configure_primary.js" | indent 4 }}

{{- if .Values.initMongodStandalone }}
  initMongodStandalone.js: |
{{ .Values.initMongodStandalone | indent 4 }}
{{- end }}

